package com.bosicc.cluedo;

import java.io.Serializable;
import java.util.ArrayList;

import com.bosicc.cluedo.PlayerPOJO.CardType;

public class GamePOJO implements Serializable{
	
	/**
	 * Autogenerated Version UID
	 */
	private static final long serialVersionUID = -2652613076649621996L;
	
	private int NumberOfPlayers;
	private int YourPlayer;
	private boolean isCreated = false;
	private PlayerPOJO[] Players;
	private CardType[][] mCards; 
	
	private ArrayList<PMovePOJO> mLogsList;
	
	public enum ShowModeType {
		ALL(0), XODIT(1), PODTVERDIL(2);

		private final int id;
		
		ShowModeType(int id) {
			this.id = id;
		}

		public int getValue() {
			return id;
		}

		public static ShowModeType findByOrdinal(int ordinal) {
			for (ShowModeType item : values()) {
				if (item.ordinal() == ordinal) {
					return item;
				}
			}
			return ALL;
		}
	}

	public GamePOJO(){
		YourPlayer = 1; // default
		NumberOfPlayers = 3; // default
		
		Players = new PlayerPOJO[6];
		// all raws for list
		mCards  = new CardType[24][6]; 
		
		for (int i=0;i<6;i++){
			for (int j=0; j<24; j++){
				mCards[j][i] = CardType.DEFAULT;
			}
			Players[i] = new PlayerPOJO();
		}
		
		mLogsList = new ArrayList<PMovePOJO>();
	}
	
	public void setNumberOfPlayers(int num){
		this.NumberOfPlayers = num;
	}
	
	public int getNumberOfPlayers(){
		return NumberOfPlayers;
	}
	
	public void setYourPlayer(int num){
		this.YourPlayer = num;
	}
	
	public int getYourPlayer(){
		return YourPlayer;
	}
	
	public void fillCardsData(){
		setCreatedGame(true);
	}
	
	public CardType[][] getCardsData(){
		return mCards;
	}
	
	public void setCardsData(int pos, int num, CardType type){
		mCards[pos][num] = type;
	}
	
	public void setRowNoData(int pos){
		for (int i=0;i<6;i++){
    		setCardsData(pos,i,CardType.NO);
    	}
	}
	
	public void setTypeinRowNoData(int pos, int num, CardType type){
		setRowNoData(pos);
		setCardsData(pos, num, type);
	}
	
	public boolean isStarted(){
		return isCreated;
	}
	
	public void setCreatedGame(boolean is){
		isCreated = is;
	}
	
	public void setPlayerNoColumn(int player){
		for (int i=0; i<24; i++){
			mCards[i][player] = CardType.NO;
		}
		
	}
	
	public ArrayList<PMovePOJO> getAllList(){
		return mLogsList;
	}
	
	public ArrayList<PMovePOJO> getCurentList(ShowModeType mode, int person){
		ArrayList<PMovePOJO> mNewList = new ArrayList<PMovePOJO>();
		switch(mode){
			case ALL:
				return this.mLogsList;
			case XODIT:{
				for (PMovePOJO item: mLogsList) {
					if (item.getPlayerXodit() == person) {
						mNewList.add(item);
					}
				}
			}
				break;
			case PODTVERDIL:{
				for (PMovePOJO item: mLogsList) {
					if (item.getPlayerPodtverdil() == person) {
						mNewList.add(item);
					}
				}
			}
				break;
		}
		
		return mNewList;
	}
	
	public void reset(){
		// Clear logs items
		mLogsList.clear();
		// Clear tabele
		for (int j=0; j<6; j++){
			for (int i=0; i<24; i++){
				mCards[i][j] = CardType.DEFAULT;
			}
			// TODO: May be remove not used Class?
			Players[j].reset();
		}
		
		// Set Flag that game not started
		this.setCreatedGame(false);
		
	}
	
}
