package com.bosicc.cluedo;

import java.io.Serializable;
import java.util.ArrayList;

import android.content.res.Resources;

import com.bosicc.cluedo.PlayerPOJO.CardType;

public class GamePOJO implements Serializable{
	
	/**
	 * Autogenerated Version UID
	 */
	private static final long serialVersionUID = -2652613076649621996L;
	
	private int NumberOfPlayers;
	private int YourPlayer;
	private boolean isCreated = false;
	private PlayerPOJO[] Players;
	private CardType[][] mCards;
	public String[] mPeopleName;
    public String[] mPeople;
    public String[] mPlace;
    public String[] mWeapon;
    public String[] mPlayersList;
    public int[] mPlayersListNum;
    
    private int version = -1;
    public int cardnum = 24;
    public int playernum = 6;
	
	private ArrayList<PMovePOJO> mLogsList;
	
	
	
	public enum ShowModeType {
		ALL(0), XODIT(1), PODTVERDIL(2);

		private final int id;
		
		ShowModeType(int id) {
			this.id = id;
		}

		public int getValue() {
			return id;
		}

		public static ShowModeType findByOrdinal(int ordinal) {
			for (ShowModeType item : values()) {
				if (item.ordinal() == ordinal) {
					return item;
				}
			}
			return ALL;
		}
	}

	public GamePOJO(){
		YourPlayer = 1; // default
		NumberOfPlayers = 3; // default
		
		Players = new PlayerPOJO[6];
		mPeopleName = new String[playernum]; //Default
		mPlayersList = new String[playernum]; //Default
		mPeople = new String[6];
		mPlace = new String[9];
		mWeapon = new String[9];
		// all raws for list
		mCards  = new CardType[cardnum][playernum]; 
		
		for (int i=0;i<playernum;i++){
			for (int j=0; j<cardnum; j++){
				mCards[j][i] = CardType.DEFAULT;
			}
			Players[i] = new PlayerPOJO();
		}
		
		mLogsList = new ArrayList<PMovePOJO>();
		
	}
	
	public void setVersion(int ver){
		version = ver;
	}
	
	public int getVersion(){
		return version;
	}
	
	public void setNumberOfPlayers(int num){
		this.NumberOfPlayers = num;
		mPeopleName = new String[NumberOfPlayers]; // Reload arrays
		mPlayersList = new String[NumberOfPlayers]; // Reload arrays
	}
	
	public int getNumberOfPlayers(){
		return NumberOfPlayers;
	}
	
	public void setPlayerName(int num, String name){
		mPeopleName[num] = name;
	}
	
	public String getPlayerName(int num){
		return mPeopleName[num];
	}
	
	public void setYourPlayer(int num){
		this.YourPlayer = num;
	}
	
	public int getYourPlayer(){
		return YourPlayer;
	}
	
	public void fillCardsData(){
		setCreatedGame(true);
	}
	
	public CardType[][] getCardsData(){
		return mCards;
	}
	
	public void setCardsData(int pos, int num, CardType type){
		mCards[pos][num] = type;
	}
	
	public void setRowNoData(int pos){
		for (int i=0;i<6;i++){
    		setCardsData(pos,i,CardType.NO);
    	}
	}
	
	public void setTypeinRowNoData(int pos, int num, CardType type){
		setRowNoData(pos);
		setCardsData(pos, num, type);
	}
	
	public void setColumnNoData(int raw){
		for (int i=0;i<cardnum;i++){
    		setCardsData(i,raw,CardType.NO);
    	}
	}
	
	public boolean isStarted(){
		return isCreated;
	}
	
	public void setCreatedGame(boolean is){
		isCreated = is;
	}
	
	public void setPlayerNoColumn(int player){
		for (int i=0; i<cardnum; i++){
			mCards[i][player] = CardType.NO;
		}
		
	}
	
	public ArrayList<PMovePOJO> getAllList(){
		return mLogsList;
	}
	
	public ArrayList<PMovePOJO> getCurentList(ShowModeType mode, int person){
		ArrayList<PMovePOJO> mNewList = new ArrayList<PMovePOJO>();
		switch(mode){
			case ALL:
				return this.mLogsList;
			case XODIT:{
				for (PMovePOJO item: mLogsList) {
					if (item.getPlayerXodit() == person) {
						mNewList.add(item);
					}
				}
			}
				break;
			case PODTVERDIL:{
				for (PMovePOJO item: mLogsList) {
					if (item.getPlayerPodtverdil() == person) {
						mNewList.add(item);
					}
				}
			}
				break;
		}
		
		return mNewList;
	}
	
	public void reset(){
		// Clear logs items
		mLogsList.clear();
		// Clear tabele
		for (int j=0; j<playernum; j++){
			for (int i=0; i<cardnum; i++){
				mCards[i][j] = CardType.DEFAULT;
			}
			// TODO: May be remove not used Class?
			Players[j].reset();
		}
		
		// Set Flag that game not started
		this.setCreatedGame(false);
		
	}
	
}
